### ISSUE TITLE
Overworld unloaded 30 sec after last person logs out

### ISSUE THREAD

**Issue by jermangarc** [dmillerw/TooMuchTime#2]
Title says it all. Happens only on server. Server unloads DIM0 after about 30 seconds, causing users not able to login into server. I really love the mod, makes the sun move slower without glitching in the sky! Tried it with no other mod installed and running latest Forge1272. Also ran it with Forge1236, same result.

**Comment by ultrasn0w** [comment]
Confirming this, getting the following crash log:
```
java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:230)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
	at weather2.ServerTickHandler.onTickInGame(ServerTickHandler.java:44)
	at weather2.EventHandlerFML.tickServer(EventHandlerFML.java:29)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_554_EventHandlerFML_tickServer_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

**Comment by thr33p10** [comment]
I have seen this same problem in SP.  Just try going to the nether for 30 seconds or so.. you can't go back to the overworld without a crash because it is unloaded by then,

**Comment by jermangarc** [comment]
Good idea, didn;t think about that. We already have chunk loaders, I'll have to reinstall and see if it works.

**Comment by AtomicBlom** [comment]
I think this should be fixed by #3. I waited 5 minutes before leaving back to the overworld with no obvious side effects.

**Comment by jermangarc** [comment]
Oh cool, thanks for the update For the meantime, keeping a chunkloader in the world is working at the moment.
